apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: istio-ingress
spec:
  timeoutSec: 42 # Backend service timeout: https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features#timeout
  connectionDraining: # Connection draining timeout: https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features#draining_timeout
    drainingTimeoutSec: 62
  logging: # HTTP access logging: https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features#http_logging
    enable: true
    sampleRate: 1.0
  healthCheck:
    checkIntervalSec: 30
    healthyThreshold: 1
    port: 8080
    requestPath: /healthz
    timeoutSec: 5
    type: HTTP
    unhealthyThreshold: 2