{{- if .Values.gke_ingress.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "gateway.name" . }}
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
    {{- toYaml .Values.gke_ingress.gateway.servers | nindent 4 }}
{{- end}}