apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: istio-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: istio-ingress
    networking.gke.io/managed-certificates: istio-ingress
    networking.gke.io/v1beta1.FrontendConfig: istio-ingress
    kubernetes.io/ingress.class: "gce"  # Updated annotation
spec:
  defaultBackend:
    service:
      name: istio-ingress
      port:
        number: 80

  rules:
  - host: '*'
    http:
      paths:
      - backend:
          service:
            name: istio-ingress
            port:
              number: 80
        path: /
        pathType: Prefix