{{- if .Values.gke_ingress.enabled}}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ include "gateway.name" . }}
spec:
  domains:
    {{- range .Values.gke_ingress.managedCertificate.domains }}
    - {{.}}
    {{- end}}
{{- end}}