name: camping-backend
hosts:
- api-camping.dev.ggorockee.com

gatewayPort:
  - number: 80
    name: http
    protocol: HTTP

virtualService:
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: camping-backend-with-go
        port:
          number: 3000
