name: kiali
hosts:
- kiali.dev.ggorockee.com

gatewayPort:
  - number: 80
    name: http
    protocol: HTTP

virtualService:
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: kiali
        port:
          number: 2001
