name: prometheus-operated
hosts:
- prom.dev.ggorockee.com

gatewayPort:
  - number: 80
    name: prometheus
    protocol: HTTP

virtualService:
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: prometheus-operated
        port:
          number: 9090
