name: teleport-cluster
hosts:
- teleport.dev.ggorockee.com

gatewayPort:
  - number: 80
    name: http
    protocol: HTTP

virtualService:
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: teleport-cluster
        port:
          number: 3080
