apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: istio-ingress-dev
  annotations:
    kubernetes.io/ingress.global-static-ip-name: istio-ingress-dev
    networking.gke.io/managed-certificates: istio-ingress-dev
    networking.gke.io/v1beta1.FrontendConfig: istio-ingress-dev
    kubernetes.io/ingress.class: "gce"  # Updated annotation
    kubernetes.io/ingress.allow-http: "true"
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: istio-ingress
            port:
              number: 80
        path: /
        pathType: Prefix
    host: "*.dev.ggorockee.com"