apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "bank-with-istio.helmLabels" . | nindent 4}}
    {{- range $index, $value := .Values.userService.labels }}
    {{ $index }}: {{ $value }}
    {{- end}}
  name: {{ .Values.userService.name }}
spec:
  selector:
    matchLabels:
      {{- include "bank-with-istio.helmLabels" . | nindent 6}}
      {{- range $index, $value := .Values.userService.labels }}
      {{ $index }}: {{ $value }}
      {{- end}}
  template:
    metadata:
      annotations:
        {{- toYaml .Values.userService.deployment.annotations  | nindent 8}}
      labels:
        {{- include "bank-with-istio.helmLabels" . | nindent 8}}
        {{- range $index, $value := .Values.userService.labels }}
        {{ $index }}: {{ $value }}
        {{- end}}
    spec:
      containers:
        - env:
            - name: VERSION
              value: v0.6.5
            - name: PORT
              value: "8080"
            - name: ENABLE_TRACING
              value: "true"
            - name: TOKEN_EXPIRY_SECONDS
              value: "3600"
            - name: PRIV_KEY_PATH
              value: /tmp/.ssh/privatekey
            - name: LOG_LEVEL
              value: info
          envFrom:
            - configMapRef:
                name: environment-config
            - configMapRef:
                name: accounts-db-config
          image: {{ printf "%s:%s@%s" .Values.userService.deployment.image.repository .Values.userService.deployment.image.tag .Values.userService.deployment.image.sha }}
          name: {{ .Values.userService.name }}
          ports:
            - containerPort: {{ .Values.userService.deployment.port.containerPort }}
              name: {{ .Values.userService.deployment.port.name }}
          readinessProbe:
            {{- toYaml .Values.userService.deployment.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.userService.deployment.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.userService.deployment.podSecurityContext | nindent 12 }}
          volumeMounts:
            - mountPath: /tmp
              name: tmp
            - mountPath: /tmp/.ssh
              name: keys
              readOnly: true
      securityContext:
        {{- toYaml .Values.userService.deployment.securityContext | nindent 12 }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      terminationGracePeriodSeconds: 5
      volumes:
        - emptyDir: {}
          name: tmp
        - name: keys
          secret:
            items:
              - key: jwtRS256.key
                path: privatekey
              - key: jwtRS256.key.pub
                path: publickey
            secretName: jwt-key
