{{- if .Values.configmap }}
{{- range .Values.configmap }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
data:
  # property-like keys; each key maps to a simple value
  {{- range $key, $value := .data }}
  {{$key}}: {{$value | quote}}
  {{- end }}
{{- end  }}
{{- end}}