{{- if .Values.secret }}
{{- range .Values.secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
type: {{ .type | default "opaque"}}
data:
  # property-like keys; each key maps to a simple value
  {{- range $key, $value := .data }}
  {{$key}}: {{$value | b64enc}}
  {{- end }}
{{- end  }}
{{- end}}