{{- if .Values.secret }}
{{ $db_full_name := include "db.fullname" . }}
{{ $release_namespace := .Release.Namespace }}
{{- range .Values.secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
type: {{ .type | default "opaque"}}
data:
  # property-like keys; each key maps to a simple value
  {{- range $key, $value := .data }}
  {{- if eq $key "POSTGRES_HOST"}}
  {{$key}}: {{ printf "%s" $db_full_name | b64enc}}
  {{- else }}
  {{$key}}: {{$value | b64enc}}
  {{- end}}
  {{- end }}
{{- end  }}
{{- end}}