{{- if .Values.statefulset.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "db.serviceAccountName" . }}
  labels:
    {{- include "db.labels" . | nindent 4 }}
  {{- with .Values.statefulset.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.statefulset.serviceAccount.automount }}
{{- end }}
