apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "istio-test-dev.fullname" . }}
spec:
  selector:
    istio: ingressgateway-dev
  servers:
  - port:
      number: 8080
      name: http
      protocol: HTTP
    hosts:
    - "demo1.dev.ggorockee.com"