account:
  name: accounts-db

  labels:
    app: accounts-db
    application: bank-of-anthos
    environment: development
    team: accounts
    tier: db

  configmap:
    name: accounts-db-config
    data:
      ACCOUNTS_DB_URI: postgresql://accounts-admin:accounts-pwd@accounts-db:5432/accounts-db
      POSTGRES_DB: accounts-db
      POSTGRES_PASSWORD: accounts-pwd
      POSTGRES_USER: accounts-admin

  service:
    ports:
      - name: tcp
        port: 5432
        protocol: TCP
        targetPort: 5432
    type: ClusterIP

  statefulset:
    replicas: 1
    labels: {}

leaderDb:
  name: &ledger-db-name ledger-db
  labels:
    app: *ledger-db-name
    team: ledger
    tier: db

  configmap:
    data:
      POSTGRES_DB: postgresdb
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_HOST_AUTH_METHOD: trust
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_URL: jdbc:postgresql://ledger-db:5432/postgresdb
      SPRING_DATASOURCE_USERNAME: admin
      
  service:
    port:
      name: tcp
      port: 5432
      targetPort: 5432
    type: ClusterIP

  statefulset:
    replicas: 1
    image:
      tag: "v0.6.5"
      sha: "sha256:cc4fd25f301ab6d46b1312244d6931babc4c6cb66c5cb6d31d4a1adfa318a321"
      repository: "us-central1-docker.pkg.dev/bank-of-anthos-ci/bank-of-anthos/ledger-db"



serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations:
    iam.gke.io/gcp-service-account: gke-workload-development@bank-of-anthos-ci.iam.gserviceaccount.com
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "bank-of-anthos"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

extraConfig:
  - name: environment-config
    data:
      LOCAL_ROUTING_NUM: "883745000"
      PUB_KEY_PATH: "/tmp/.ssh/publickey"
  - name: service-api-config
    data:
      TRANSACTIONS_API_ADDR: "ledgerwriter:8080"
      BALANCES_API_ADDR: "balancereader:8080"
      HISTORY_API_ADDR: "transactionhistory:8080"
      CONTACTS_API_ADDR: "contacts:8080"
      USERSERVICE_API_ADDR: "userservice:8080"
  - name: demo-data-config
    data:
      USE_DEMO_DATA: "True"
      DEMO_LOGIN_USERNAME: "testuser"
      # All demo user accounts are hardcoded to use the login password 'bankofanthos'
      DEMO_LOGIN_PASSWORD: "bankofanthos"