apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "bank-with-istio.helmLabels" . | nindent 4}}
    {{- range $index, $value := .Values.transactionhistory.labels }}
    {{ $index }}: {{ $value }}
    {{- end}}
  name: {{ .Values.transactionhistory.name }}
spec:
  selector:
    matchLabels:
      {{- include "bank-with-istio.helmLabels" . | nindent 6}}
      {{- range $index, $value := .Values.transactionhistory.labels }}
      {{ $index }}: {{ $value }}
      {{- end}}
  template:
    metadata:
      annotations:
        {{- toYaml .Values.transactionhistory.deployment.annotations | nindent 8}}
      labels:
        {{- include "bank-with-istio.helmLabels" . | nindent 8}}
        {{- range $index, $value := .Values.transactionhistory.labels }}
        {{ $index }}: {{ $value }}
        {{- end}}
    spec:
      containers:
        - env:
            - name: VERSION
              value: v0.6.5
            - name: PORT
              value: "8080"
            - name: ENABLE_TRACING
              value: "true"
            - name: ENABLE_METRICS
              value: "true"
            - name: POLL_MS
              value: "100"
            - name: CACHE_SIZE
              value: "1000"
            - name: CACHE_MINUTES
              value: "60"
            - name: HISTORY_LIMIT
              value: "100"
            - name: JVM_OPTS
              value: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Xms256m -Xmx512m
            - name: LOG_LEVEL
              value: info
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - configMapRef:
                name: environment-config
            - configMapRef:
                name: ledger-db-config
          image: {{ printf "%s:%s@%s" .Values.transactionhistory.deployment.image.repository .Values.transactionhistory.deployment.image.tag .Values.transactionhistory.deployment.image.sha }}
          livenessProbe:
            {{- toYaml .Values.transactionhistory.deployment.livenessProbe | nindent 12 }}
          name: {{ .Values.transactionhistory.name }}
          readinessProbe:
            {{- toYaml .Values.transactionhistory.deployment.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.transactionhistory.deployment.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.transactionhistory.deployment.podSecurityContext | nindent 12 }}
          startupProbe:
            {{- toYaml .Values.transactionhistory.deployment.startupProbe | nindent 12 }}
          volumeMounts:
            - mountPath: /tmp
              name: tmp
            - mountPath: /tmp/.ssh
              name: publickey
              readOnly: true
      securityContext:
        {{- toYaml .Values.transactionhistory.deployment.securityContext | nindent 8 }}
      serviceAccountName: bank-of-anthos
      terminationGracePeriodSeconds: 5
      volumes:
        - emptyDir: {}
          name: tmp
        - name: publickey
          secret:
            items:
              - key: jwtRS256.key.pub
                path: publickey
            secretName: jwt-key
