apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "airbnb-server.fullname" . }}
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 8080
      name: http
      protocol: HTTP
    hosts:
    - "airbnb.dev.ggorockee.com"