{{- $pvc_enabled := .Values.pvc.enabled -}}
{{- $pvc_name := .Values.pvc.name -}}
{{- $configmap_enabled := .Values.config.enabled -}}
{{- $configmap_name := .Values.config.name -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}
spec:
  replicas: {{.Values.deployment.replicas}}
  selector:
    matchLabels:
      {{- include "gke-pd-existing-sc-standard-rwo.selectorLabels" . | nindent 6}}
  strategy:
    type: {{.Values.deployment.strategy}}
  template:
    metadata:
      labels:
        {{- include "gke-pd-existing-sc-standard-rwo.selectorLabels" . | nindent 8}}
    spec:
      containers:
        - name: {{.Release.Name}}
          image: {{printf "%s:%s" .Values.deployment.image.repository .Values.deployment.image.tag|default "latest"}}
          envFrom:
            - secretRef:
                name: {{.Release.Name}}
          {{- with .Values.deployment.port}}
          ports:
            {{- range .}}
            - containerPort: {{.}}
            {{- end}}
          {{- end}}
          volumeMounts:
            {{- if $pvc_enabled }}
            - mountPath: /var/lib/mysql
              name: {{.Values.deployment.volume.name}}
            {{- end}}
            {{- if $configmap_enabled}}
            - mountPath: /docker/entrypoint-initdb.d
              name: {{$configmap_name}}
            {{- end}}
      {{- with .Values.deployment.volume}}
      volumes:
        - name: {{.name}}
        {{- if $pvc_enabled }}
          persistentVolumeClaim:
            claimName: {{$pvc_name}}
        {{- end}}
        {{- if $configmap_enabled}}
        - name: {{$configmap_name}}
          configMap:
            name: {{$configmap_name}}
        {{- end }}

      {{- end}}
