apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: basic-applicationsets
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/ggorockee/devops/
        revision: HEAD
        files:
          - path: argocd/env/dev/app/*.yaml
  template:
    metadata:
      name: '{{project}}-{{app_name}}'
      namespace: argocd
    spec:
      project: '{{project}}'
      source:
        repoURL: https://github.com/ggorockee/devops/
        targetRevision: HEAD
        path: 'helm-repository/apps/{{chart_name}}'
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - Replace=true
      ignoreDifferences:
      - group: apps
        kind: Deployment
        name: loadgenerator
        namespace: '{{namespace}}'
        jsonPointers:
        - /spec/template/spec/securityContext
      
      - group: apps
        kind: StatefulSet
        name: accounts-db
        namespace: '{{namespace}}'
        jsonPointers:
        - /spec/template/spec/serviceAccount

      - group: apps
        kind: StatefulSet
        name: ledger-db
        namespace: '{{namespace}}'
        jsonPointers:
        - /spec/template/spec/serviceAccount
