apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istiod
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/ggorockee/devops/
        revision: main
        files:
          - path: argocd/env/istiod.yaml

  template:
    metadata:
      name: '{{app_name}}'
      namespace: argocd
    spec:
      project: '{{project}}'
      source:
        repoURL: https://github.com/ggorockee/devops/
        targetRevision: HEAD
        path: 'helm-repository/{{chart_name}}'
        helm:
          valueFiles:
            - values.yaml

      ignoreDifferences:
        - group: admissionregistration.k8s.io
          kind: ValidatingWebhookConfiguration
          name: istio-validator-istio-system
          jsonPointers:
            - /webhooks/0/failurePolicy

        - group: apps
          kind: Deployment
          name: istiod
          jqPathExpressions:
            - '.spec.template.spec.containers[].env[]'

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
