apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-base
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/ggorockee/devops/
        revision: HEAD
        files:
          - path: argocd/env/istio-base.yaml
  template:
    metadata:
      name: '{{app_name}}'
      namespace: argocd
    spec:
      project: '{{project}}'
      source:
        repoURL: https://github.com/ggorockee/devops/
        targetRevision: HEAD
        path: 'helm-repository/{{chart_name}}'
        helm:
          valueFiles:
            - values.yaml
      ignoreDifferences:
      - group: admissionregistration.k8s.io
        kind: ValidatingWebhookConfiguration
        name: istio-validator-istio-system
        jsonPointers:
          - /webhooks/0/failurePolicy
      - group: admissionregistration.k8s.io
        kind: ValidatingWebhookConfiguration
        name: istiod-default-validator
        jsonPointers:
          - /webhooks/0/failurePolicy
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true