{{ $fullname := include "bookinfo.fullname" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-ratings" $fullname}}
  labels:
    {{- include "bookinfo.labels" . | nindent 4 }}
spec:
  {{- if not .Values.ratings.autoscaling.enabled }}
  replicas: {{ .Values.ratings.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- toYaml .Values.ratings.podLabels | nindent 6 }}
  template:
    metadata:
      {{- with .Values.ratings.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- with .Values.ratings.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.ratings.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.ratings.serviceAccount.name }}
      securityContext:
        {{- toYaml .Values.ratings.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ printf "%s-ratings" .Chart.Name }}
          securityContext:
            {{- toYaml .Values.ratings.securityContext | nindent 12 }}
          image: "{{ .Values.ratings.image.repository }}:{{ .Values.ratings.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.ratings.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.ratings.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.ratings.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.ratings.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.ratings.resources | nindent 12 }}
          {{- with .Values.ratings.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.ratings.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ratings.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ratings.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ratings.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
