{{ $name := include "bookinfo.name" . }}
{{- if .Values.ratings.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ printf "%s-ratings" $name}}
  labels:
    {{- with .Values.ratings.podLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.ratings.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.ratings.serviceAccount.automount }}
{{- end }}
