apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: istio-ingress-dev
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: istio-ingress-dev
    app.kubernetes.io/version: 1.22.1
    argocd.argoproj.io/instance: istio-ingress-dev
    helm.sh/chart: istio-ingress-1.22.1
    istio: ingressgateway-dev
  name: istio-ingress-dev
  namespace: istio-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: istio-ingress-dev
      istio: ingressgateway-dev
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        inject.istio.io/templates: gateway
        prometheus.io/path: /stats/prometheus
        prometheus.io/port: '15020'
        prometheus.io/scrape: 'true'
        sidecar.istio.io/inject: 'true'
      creationTimestamp: null
      labels:
        app: istio-ingress-dev
        istio: ingressgateway-dev
        sidecar.istio.io/inject: 'true'
    spec:
      containers:
        - image: auto
          imagePullPolicy: Always
          name: istio-proxy
          ports:
            - containerPort: 15090
              name: http-envoy-prom
              protocol: TCP
          resources:
            limits:
              cpu: '2'
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 1337
            runAsNonRoot: true
            runAsUser: 1337
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        sysctls:
          - name: net.ipv4.ip_unprivileged_port_start
            value: '0'
      serviceAccount: istio-ingress
      serviceAccountName: istio-ingress
      terminationGracePeriodSeconds: 30
