name: prometheus-operator-grafana
hosts:
- grafana.dev.ggorockee.com
- prom.dev.ggorockee.com

gatewayPort:
  - number: 80
    name: http
    protocol: HTTP

virtualService:
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: prometheus-operator-grafana
        port:
          number: 80

    - destination:
        host: prometheus-operated
        port:
          number: 9090
