{{- range $index, $config := .Values.extraConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{$config.name}}
  labels:
    {{- include "bank-with-istio.labels" . | nindent 4 }}
data:
  {{- toYaml $config.data | nindent 2}}
---
{{- end}}